"""empty message

Revision ID: 484471720d21
Revises: 
Create Date: 2022-03-26 14:17:51.071166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484471720d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_proj', sa.Column('cost_to_complete', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('funding', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('physical', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('procurement', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('completed_proj', sa.Column('revised_date', sa.Date(), nullable=True))
    op.add_column('completed_proj', sa.Column('revised_sum', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('status', sa.String(length=80), nullable=True))
    op.add_column('completed_proj', sa.Column('time_elapsed', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_proj', 'time_elapsed')
    op.drop_column('completed_proj', 'status')
    op.drop_column('completed_proj', 'revised_sum')
    op.drop_column('completed_proj', 'revised_date')
    op.drop_column('completed_proj', 'remarks')
    op.drop_column('completed_proj', 'procurement')
    op.drop_column('completed_proj', 'physical')
    op.drop_column('completed_proj', 'funding')
    op.drop_column('completed_proj', 'cost_to_complete')
    # ### end Alembic commands ###
