"""empty message

Revision ID: 507cc15ff48a
Revises: cbd5ab6382a3
Create Date: 2021-03-17 19:36:50.011593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '507cc15ff48a'
down_revision = 'cbd5ab6382a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    op.drop_column('user', 'ret_notice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ret_notice', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('user', sa.Column('age', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
