"""empty message

Revision ID: 563e910816cc
Revises: 
Create Date: 2021-01-15 12:46:24.496234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563e910816cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadcondition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg', sa.String(length=50), nullable=True),
    sa.Column('road_no', sa.String(length=50), nullable=True),
    sa.Column('road_name', sa.String(length=50), nullable=True),
    sa.Column('link_ref', sa.String(length=50), nullable=True),
    sa.Column('sect_ref', sa.String(length=50), nullable=True),
    sa.Column('fr_om', sa.String(length=50), nullable=True),
    sa.Column('t_o', sa.String(length=50), nullable=True),
    sa.Column('start', sa.String(length=50), nullable=True),
    sa.Column('end', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('width', sa.String(length=50), nullable=True),
    sa.Column('surf_type', sa.String(length=50), nullable=True),
    sa.Column('cond_score', sa.String(length=50), nullable=True),
    sa.Column('iri', sa.String(length=50), nullable=True),
    sa.Column('cond', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadcondition')
    # ### end Alembic commands ###
