"""Initial migration.

Revision ID: 5f627df29d75
Revises: 484471720d21
Create Date: 2022-04-06 15:04:31.532932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f627df29d75'
down_revision = '484471720d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_proj', sa.Column('activity', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('phy', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_proj', 'phy')
    op.drop_column('completed_proj', 'activity')
    # ### end Alembic commands ###
