"""empty message

Revision ID: 8cb10389ee5f
Revises: d8ee7fe79e02
Create Date: 2021-02-04 10:35:58.100593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cb10389ee5f'
down_revision = 'd8ee7fe79e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadcondition2_k19', 'end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadcondition2_k19', sa.Column('end', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
