"""empty message

Revision ID: a8f398a3bfbc
Revises: e399598a1eb6
Create Date: 2021-04-18 06:09:01.636811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f398a3bfbc'
down_revision = 'e399598a1eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ongoing_proj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('project', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('amt_to_date', sa.String(length=50), nullable=True),
    sa.Column('video_title', sa.String(length=300), nullable=True),
    sa.Column('video_link', sa.String(length=250), nullable=True),
    sa.Column('video_description', sa.Text(), nullable=True),
    sa.Column('video_thumb', sa.String(length=50), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ongoing_proj')
    # ### end Alembic commands ###
