"""empty message

Revision ID: cbd5ab6382a3
Revises: 
Create Date: 2021-03-17 19:12:56.964349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd5ab6382a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('ref_no', sa.String(length=120), nullable=False),
    sa.Column('acc_gen_no', sa.String(length=120), nullable=False),
    sa.Column('ssf_no', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=120), nullable=False),
    sa.Column('job_pos', sa.String(length=120), nullable=False),
    sa.Column('date_engaged', sa.Date(), nullable=False),
    sa.Column('pres_appt', sa.Date(), nullable=False),
    sa.Column('station', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('image_file', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    # ### end Alembic commands ###
