"""empty message

Revision ID: ee9eba4e3f2e
Revises: de914d3cec18
Create Date: 2021-04-24 12:18:47.331016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9eba4e3f2e'
down_revision = 'de914d3cec18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_proj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('project', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('amt_to_date', sa.String(length=50), nullable=True),
    sa.Column('video_title', sa.String(length=300), nullable=True),
    sa.Column('video_link', sa.String(length=250), nullable=True),
    sa.Column('video_description', sa.Text(), nullable=True),
    sa.Column('video_thumb', sa.String(length=50), nullable=True),
    sa.Column('image_one', sa.String(length=120), nullable=True),
    sa.Column('image_two', sa.String(length=120), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_proj')
    # ### end Alembic commands ###
