"""empty message

Revision ID: fd1ae5015691
Revises: 
Create Date: 2020-12-27 14:04:41.139440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1ae5015691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asphalticoverlay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('construction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preconstruction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regravelling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehabilitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resealing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resurfacing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('upgrading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('image_file', sa.String(length=30), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_contract', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('contract_sum', sa.String(length=50), nullable=True),
    sa.Column('contractor', sa.String(length=120), nullable=True),
    sa.Column('date_commenced', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('video_title', sa.String(length=300), nullable=True),
    sa.Column('video_link', sa.String(length=250), nullable=True),
    sa.Column('video_description', sa.Text(), nullable=True),
    sa.Column('video_thumb', sa.String(length=50), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('rank', sa.String(length=40), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('date_app', sa.Date(), nullable=False),
    sa.Column('tele_no', sa.Integer(), nullable=False),
    sa.Column('leave_cat', sa.String(length=30), nullable=False),
    sa.Column('no_of_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('supp_info', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('mobile_no', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('days_proceed', sa.Integer(), nullable=False),
    sa.Column('effec_date', sa.Date(), nullable=False),
    sa.Column('resump_date', sa.Date(), nullable=False),
    sa.Column('outs_days', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('leave')
    op.drop_table('contract')
    op.drop_table('user')
    op.drop_table('upgrading')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('resurfacing')
    op.drop_table('resealing')
    op.drop_table('repairs')
    op.drop_table('rehabilitation')
    op.drop_table('regravelling')
    op.drop_table('preconstruction')
    op.drop_table('construction')
    op.drop_table('asphalticoverlay')
    # ### end Alembic commands ###
